### ISSUE TITLE
2.9.0: plexus-compiler-eclipse lacks dependencies; doesn't work with maven-compiler-plugin 3.8.1

### ISSUE THREAD

**Issue by tomaswolf** [codehaus-plexus/plexus-compiler#166]
Trying to use plexus-compiler-eclipse 2.9.0 with maven-compiler-plugin 3.8.1 leads to
```
org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile: java.lang.NoSuchMethodError: 'java.lang.String org.codehaus.plexus.compiler.CompilerConfiguration.getWarnings()'
```
with stack trace
```
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.codehaus.plexus.compiler.CompilerConfiguration.getWarnings()'
15:24:41      at org.codehaus.plexus.compiler.eclipse.EclipseJavaCompiler.performCompile (EclipseJavaCompiler.java:132)
15:24:41      at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1134)
15:24:41      at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
```
and reports
```
15:24:41  [ERROR] urls[1] = file:.../.repository/org/codehaus/plexus/plexus-compiler-eclipse/2.9.0/plexus-compiler-eclipse-2.9.0.jar
...
15:24:41  [ERROR] urls[17] = file:.../.repository/org/codehaus/plexus/plexus-compiler-api/2.8.4/plexus-compiler-api-2.8.4.jar
15:24:41  [ERROR] urls[18] = file:.../.repository/org/codehaus/plexus/plexus-compiler-manager/2.8.4/plexus-compiler-manager-2.8.4.jar
15:24:41  [ERROR] urls[19] = file:.../.repository/org/codehaus/plexus/plexus-compiler-javac/2.8.4/plexus-compiler-javac-2.8.4.jar
```
plexus-compiler-eclipse 2.9.0 depends on plexus-compiler-api 2.9.0, but doesn't declare this dependency in the pom.xml. So one ends up with inconsistent versions.

Users would have to override the maven-compiler-plugin config by not only adding the dependency to plexus-compiler-eclipse:2.9.0 but also to plexus-compiler-api:2.9.0.

I think the dependency should be declared.

**Comment by pzygielo** [comment]
Related:
- #162
