### ISSUE TITLE
ErrorProne compiler does not work in plexus-compiler-2.8.7 version

### ISSUE THREAD

**Issue by pzygielo** [codehaus-plexus/plexus-compiler#95]
```
[WARNING] Error injecting: org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne
java.lang.NoClassDefFoundError: org/codehaus/plexus/compiler/javac/InProcessCompiler
```
but it fails compilation with
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ...: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile failed: A required class was missing while executing org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile: org/codehaus/plexus/compiler/javac/InProcessCompiler
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-compiler-plugin:3.8.1
...
```

**Comment by pzygielo** [comment]
Hmmm - seems that explicit dependency in maven-compiler-plugin:
```xml
                            <dependency>
                                <groupId>org.codehaus.plexus</groupId>
                                <artifactId>plexus-compiler-javac</artifactId>
                            </dependency>
```
in corresponding version helps. Never used both of them in the same m-compiler-p, so perhaps it's fine and works as designed.
