### ISSUE TITLE
An API incompatibility was encountered after upgrading plexus-compiler-eclipse from 2.12.1 to 2.13.0

### ISSUE THREAD

**Issue by nbauma109** [codehaus-plexus/plexus-compiler#253]
I was using this maven config:

```xml
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.10.1</version>
  <configuration>
    <compilerId>eclipse</compilerId>
    <release>17</release>
  </configuration>
  <dependencies>
    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-compiler-eclipse</artifactId>
      <version>2.12.1</version>
    </dependency>
  </dependencies>
</plugin>
```

After dependabots PR [Bump plexus-compiler-eclipse from 2.12.1 to 2.13.0](https://github.com/nbauma109/jd-core-v0/pull/70), I received this error:

`Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project jd-core-v0: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile: java.lang.NoSuchMethodError: 'void org.codehaus.plexus.compiler.eclipse.EclipseJavaCompiler.logCompiling(java.lang.String[], org.codehaus.plexus.compiler.CompilerConfiguration)'`

Any doc available to help migrate to new API ?

**Comment by pzygielo** [comment]
Would it help to override also **OTHER** plexus-compiler dependencies, not just one?
I'm using
```xml
                        <dependencies>
                            <dependency>
                                <groupId>org.codehaus.plexus</groupId>
                                <artifactId>plexus-compiler-api</artifactId>
                                <version>${plexus.compiler.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.codehaus.plexus</groupId>
                                <artifactId>plexus-compiler-manager</artifactId>
                                <version>${plexus.compiler.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.codehaus.plexus</groupId>
                                <artifactId>plexus-compiler-javac</artifactId>
                                <version>${plexus.compiler.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.codehaus.plexus</groupId>
                                <artifactId>plexus-compiler-eclipse</artifactId>
                                <version>${plexus.compiler.version}</version>
                            </dependency>
                        </dependencies>
```
and haven't encountered _An API incompatibility_ after upgrade to 2.13.0.

**Comment by nbauma109** [comment]
Thanks, all good now !
